name = "ChaosGames"
uuid = "b4d19e2c-33e2-4df5-9897-699de9e47e3f"
authors = ["Iain <iain.best@hotmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
